version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    env_file:
      - .env.dev
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - ./my-react-app/build:/app/build
    depends_on:
      - web
      # - frontend

  ml:
    build:
      context: ml
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose Flask app port
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  # frontend:
  #   build: 
  #     context: ./my-react-app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - web

volumes:
  postgres_data:
